### ISSUE TITLE
Missing `adminstyle.php`

### ISSUE THREAD

**Issue by flydev-fr** [baumrock/AdminStyleHello#1]
~~Bernhard, where does the file `adminstyle.php` come from ?~~

Ok, from the PR..

The following line shouldn't be `wire('config')` instead of `$wire` as you call it from outside the object ?

https://github.com/baumrock/AdminStyleHello/blob/a44a7b8c44673d4a1bc7c979ac6dac4e12923e01/AdminStyleHello.module.php#L11

And just a suggestion, if it make sense as I lost two minutes figuring out why it was not loading my styles:

The following line is _plural_ in `AdminStyleRock` - the dir containing the styles - `style` vs `styles`

https://github.com/baumrock/AdminStyleHello/blob/a44a7b8c44673d4a1bc7c979ac6dac4e12923e01/AdminStyleHello.module.php#L34

otherwise, everything is good :)

https://github.com/ryancramerdesign/Less/pull/2#issue-1401933280

**Comment by BernhardBaumrock** [comment]
Hey @flydev-fr thx for your comment.

I don't think that there's anything bad about $this->wire here. I must admit it felt weird at first, but it works and $this is an instance of ProcessWire\Modules so it's doing exactly what it should and I think it's the best solution (unless I'm missing something?)

> The following line is plural in AdminStyleRock - the dir containing the styles - style vs styles

Good spot. I think "style" is the better wording but it's not a convention at all. Every developer can freely choose a name for the folder - he/she just has to choose the same folder name in ready()

**Comment by BernhardBaumrock** [comment]
@flydev-fr wouldn't wire('config') mean that FunctionsAPI needs to be turned on? $this->wire works always!

**Comment by BernhardBaumrock** [comment]
@flydev-fr I see that you named it "styles" in your module --> In my module I don't plan to add multiple styles in the folder, so I called it "style". The folder would even not be necessary at all... Not sure what would be the best, but I think after all it does not really matter :)

**Comment by flydev-fr** [comment]
About the folder name it doesn't matter yes, just reporting it as I was following your existing code and I get confused some minutes and for getting consistant  sample code.

And for wire(), its not really related to functionApi _(I never used that)_, but it's used to get wire API variables from specific scope (its more PHP things than other). 
I will try to debug the line because with `$this->wire->config->paths` I dont get the full path, where with `wire('config')` I get it. At first I thought it was working because even if we didn't return the full path, we had the relative path.

> $this is an instance of ProcessWire\Modules

I understand yes, but the line is outside the module déclaration, but it may receive it from the namespace.

**Comment by BernhardBaumrock** [comment]
thx @flydev-fr I can confirm that wire()->config works as well (also with functions api turned off)! Maybe that would be better. Note that I prefer wire()->config over wire('config') as the former makes my IDE understand what's going on and help me with intellisense :)

> I understand yes, but the line is outside the module déclaration, but it may receive it from the namespace.

Yeah it's outside of the class but I don't think that we can't do that :) I'm not refering to AdminStyleHello with $this of course. That would be nonesense. But as we are within a wire object (whichever it may be) $this->wire should also work.

Maybe someone else can explain that better...

**Comment by BernhardBaumrock** [comment]
Hey @flydev-fr I've just pushed your proposed syntax update. I think wire() is better than $this - at least it's more obvious what it does so it's preferable.
